### PR TITLE
Improve "no pass" demo email

### PR DESCRIPTION
**Pull request by karenword**
Adjusts language consistent with invitation to return vs "no pass", expands recommendations for rationale content.

@murraycadzow does this look like it might have worked better for you?

### CODE REVIEW

**Comment by karenword** [comment]
Also pinging @ChristinaLK and @raynamharris

**Comment by murraycadzow** [comment]
Yes I think that would have worked better for me
thanks

**Comment by karenword** [comment]
There is also a Spanish language version of this template that will need to be updated, too.

**Comment by ChristinaLK** [comment]
Looks good to me!

**Comment by raynamharris** [comment]
LGTM!

**Comment by maneesha** [comment]
Thanks @karenword  @murraycadzow  @ChristinaLK @raynamharris

**Pull request merged**
