### PR TITLE
clarify Business Admin should receive requests

### PR DESCRIPTION
**Pull request by elizabethwilliams8**
Lex pointed out that it is unclear here to the community who to send the documentation (receipts, etc...) to in order to start the reimbursement process. He guessed me because he is more aware of staff rules, but I think clarifying here is a good idea. These additions reflect the process that has been and is currently followed for community reimbursement.

### CODE REVIEW

**Comment by tracykteal** [comment]
Should we add 'submitted to the Business Administrator at finance@carpentries.org'?

**Comment by elizabethwilliams8** [comment]
Great point! .... how do I change the commit?

**Comment by maneesha** [comment]
Thanks @elizabethwilliams8 
We can merge once @smcclatchy  has reviewed.

**Comment by smcclatchy** [comment]
Looks good to me. Do I need to do anything else here?

**Pull request merged**
