### PR TITLE
Restructure starting points for demos

### PR DESCRIPTION
**Pull request by ErinBecker**
Fixes https://github.com/carpentries/handbook/issues/250#issuecomment-416420009

### CODE REVIEW

**Comment by ErinBecker** [comment]
@maneesha - this is ready for review.

**Comment by maneesha** [comment]
@ErinBecker  Have you looked at what this looks like when rendered? From what I've seen tables do not format properly in readthedocs.

**Comment by maneesha** [comment]
Ok @ErinBecker  I just pulled your branch and tried building the site.  It doesn't look good :-(

image



I have not found a way to make Read the Docs play nice with tables.  [I tried this somewhere else and ended up giving up.](https://github.com/carpentries/handbook/issues/9)
Do you have ideas of other ways to organize this?  Or maybe have the handbook link to a file in this repo, rather than trying to fit it in the handbook itself?

**Comment by maneesha** [comment]
@ErinBecker  There are apparently some issues with building on Macs.  See https://github.com/carpentries/handbook/issues/193 and https://github.com/carpentries/handbook/pull/194

I've noted in both those issues/PRs that I don't know enough about Macs to comment or accept them.

**Comment by jduckles** [comment]
Looking into this, the reason Erin's tables aren't rendering is ReadTheDocs uses CommonMark to render Markdown to HTML, which oddly enough, doesn't support Markdown table syntax 🤦‍♂️ . There is a [Sphinx extension](https://github.com/ryanfox/sphinx-markdown-tables) that fixes this shortcoming of CommonMark, which I just tested. I'm adding it to the requirements and will push it to the build server and `conf.py`.

If you already have a build environment set, you'll need to add it with:
```
pip install sphinx-markdown-tables
```
Example build of Erin's tables:
image

**Comment by jduckles** [comment]
This plugin is installed in the build environment and the install instructions are updated to use a `requirements.txt` so have at it with tables 😁 now.

**Comment by maneesha** [comment]
Thanks @jduckles   I'll review this shortly.  I should have come to you months and months ago!

**Comment by ErinBecker** [comment]
Wow, thanks @jduckles!! 

@maneesha - please go ahead and merge. I think this is a vast improvement over the current content of that section. I agree that we should look into ways of improving the aesthetics, but let's get the info out there and put in a new issue for changing the table width.

**Comment by ErinBecker** [comment]
FYI - @karenword for coordinating with Trainers.

**Pull request merged**
