### PR TITLE
Adding CoC membership agreement

### PR DESCRIPTION
**Pull request by malvikasharan**
Please feel free to suggest a different location for this file, but so far this looks like the right pace.

### CODE REVIEW

**Comment by maneesha** [comment]
@kariljordan  Could you review this before I merge?

**Comment by kariljordan** [comment]
@maneesha I revised some of the language for consistency. It's ready!

**Comment by maneesha** [comment]
Thanks @malvikasharan  and @kariljordan !

**Comment by malvikasharan** [comment]
Yay!!!!!

**Pull request merged**
