### PR TITLE
Update communications section of the handbook

### PR DESCRIPTION
**Pull request by serahrono**
# Before:

Screenshot 2019-07-04 at 13 24 32

# After:

Screenshot 2019-07-04 at 13 27 36

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks for doing all this @serahrono !! 
I'll take some time this week to look this over to be sure the formatting is OK, address links that this may break, etc.

**Comment by serahrono** [comment]
Thanks Maneesha, I'll also do due diligence and add those fixes where I find them in the next day or so. Thanks for pointing that out.

**Comment by tracykteal** [comment]
Thanks @serahrono for this PR. Really nice organization that provides good access to the information and resources, and reflects current communication strategy updates.

**Comment by serahrono** [comment]
Hi @maneesha , I have now checked links that would break either here in The Handbook (found none) or in our website (found some and submitted a PR to fix them here https://github.com/carpentries/carpentries.org/pull/489).

I think we are ready to merge it now. 

Thank you

**Comment by maneesha** [comment]
For my own reference, links on the other website that will need to be updated once this is merged.  I will work on this tomorrow.

**In carpentries.org**

- ./_posts/2018/12/2018-12-07-more-than-workshops.md:https://docs.carpentries.org/topic_folders/communications/slack-and-email.html
- ./_posts/2018/12/2018-12-07-more-than-workshops.md:https://docs.carpentries.org/topic_folders/communications/submit_blog_post.html
- ./_posts/2018/10/2018-10-24-ec-elections.md:https://docs.carpentries.org/topic_folders/communications/submit_blog_post.html
- ./pages/connect.md:https://docs.carpentries.org/topic_folders/communications/slack-and-email.html

I don't see any links to the communications section of the handbook in the three lesson program sites.

**Comment by maneesha** [comment]
Oops -  I didn't see Serah's earlier comment noting she had already found these links!  There might be a bit of a conflict as the handbook takes up to 24 hours to propagate while the carpentries.org  website updates right away.  I'm going to merge these on Friday so the conflict will resolve itself over the weekend.

**Pull request merged**
