### PR TITLE
Renamed mentoring folder to instructor development

### PR DESCRIPTION
**Pull request by kariljordan**
Added discussion session checklist

@tobyhodges can you review and merge? Trying to get the handbook updated in all the places and make the changes to the instructor-development repo. Thanks!

### CODE REVIEW

**Comment by maneesha** [comment]
Pinging @tobyhodges -- see above.

Also - would you like the item in the left side TOC in the handbook to also be renamed "Instructor Development"?   I can do that - it's a quick & easy fix; just want to make sure.

**Comment by tobyhodges** [comment]
Please go ahead with that renaming as suggested, Maneesha.

**Comment by maneesha** [comment]
I was doing some work on a local branch to fix some things here -- I want to look at everything before merging this.

**Comment by maneesha** [comment]
Closing this as this was a bit more complicated than it would seem and  was fixed with a bunch of commits on 2018-11-29

**Pull request closed without merging**
