### PR TITLE
Updated to address issues enforcing CoC/adjudicating reported violations

### PR DESCRIPTION
**Pull request by kariljordan**
*****DO NOT MERGE THIS PR UNTIL 2018/09/11*****

@tracykteal @karinlag 
Here is the PR to update the CoC. @tracykteal, please confirm if they layout and change log are what you wanted. @maneesha do you want us to be consistent with the numbering systems? In other parts of the handbook, roman numerals are used. Some parts use bullets, and others use numeric.

### CODE REVIEW

**Comment by tracykteal** [comment]
Yes, this format is great. The update log refers just to changes around reporting. Changes were also made to the CoC policy text. Could you add a sentence about what those changes are? Also could you reference who made the changes, 'Updates made on 2018.. by the Code of Conduct committee in consultation with Otter Technologies ...". People on the CoC could potentially be individually listed also, e.g. "by the Code of Conduct committee (Karin Lagesen, Simon ...) ..."

Currently each section (Policy, Reporting Guidelines, Enforcement manual) has a section at the end that says "This document is adapted from guidelines.." Let's add that same log message "Updates made on 2018..." to each of the sections.

Otherwise, looks good, and this PR clearly shows what changes were made, and documents the updates. Thanks!

**Comment by karinlag** [comment]
I will review these tomorrow evening (friday, daytime US).

**Comment by karinlag** [comment]
This looks good to me. The only thing I'd like to suggest is to add the original attribute (This document is adapted from guidelines written by.. etc) below the 2018 update listing. This one is based on the old one, thus not completely original, and I think the people contributing to the 2016 version deserve to be acknowledged.

**Comment by tracykteal** [comment]
Ah, yes, I see all the acknowledgements are at the bottom of the CoC, rather than in the different sections now. That works. That's a good idea for the log file. Let's add the old acknowledgements to the top of the log file. Then this update is the second entry in the Update log. 

e.g 

Update Log:
- Policy, reporting guidelines and enforcement manual released on ... . They are adapted from (list of things they're adapted from from those various sections) with contributions from (list of people who contributed from those various sections)
- Updated on 2018-09-11 ...

**Comment by karinlag** [comment]
@tracykteal That is exactly what I was thinking.  I think we can put 2016-11-21 as the date on that one, considering https://datacarpentry.org/blog/2016/11/how-we-wrote-our-code-of-conduct

**Comment by karinlag** [comment]
@kariljordan I have reviewed them, and they look good. Thanks!

**Pull request merged**
