### PR TITLE
added the actual survey link

### PR DESCRIPTION
**Pull request by sheraaron**

### CODE REVIEW

**Comment by maneesha** [comment]
I would recommend *not* having the actual survey link.  We do not want them to click on https://www.surveymonkey.com/r/D7LM7DW?workshop_id=[workshop_id_value]

Rather we want them to click on it through the github webpage so that the `workshop_id_value` variable gets filled in.  (Note I think that the github template needs to be set up to make this happen - that's a separate issue)

**Comment by sheraaron** [comment]
Ahhhh ok! I remember we discussed this on our call. @maneesha what should I be doing now being that we don't have it connected to GitHub currently?

**Comment by maneesha** [comment]
I changed this so it refers to the website, rather than to the direct survey link. That way whenever it is set up to use the slug, we don't have to change this again.

**Comment by sheraaron** [comment]
@maneesha when you say "found on the link above" which link are you referencing? There are several links above this line. Do we need to change some of the verbiage to indicate where to go?

**Pull request merged**
