### PR TITLE
Include note about red/green stickies

### PR DESCRIPTION
**Pull request by angela-li**
See carpentries/instructor-training#1032 for more information about this change

### CODE REVIEW

**Comment by maneesha** [comment]
This is a great suggestion, @angela-li 
I'd want to expand this a bit, as red-green isn't the only kind of colorblindness.  I'm not an expert on this at all so I started reading more.  See, for example:  https://nei.nih.gov/health/color_blindness/facts_about

Perhaps we could also make other suggestions like:
* Offer sticky notes in two distinct shapes 
* Use a heavy marker to draw symbols on the sticky notes to convey meaning.

Any other ideas?  Angela, if you want to update this PR, then we can merge.

**Comment by angela-li** [comment]
Thanks for the feedback @maneesha! I updated the note to reference all colorblindness, and included the suggestions you offered. Let me know if this looks good to you!

**Comment by kariljordan** [comment]
These recommendations are great. Thank you @angela-li and @maneesha!

**Comment by maneesha** [comment]
Thank you @angela-li !!

**Pull request merged**
