### PR TITLE
self vs centrally organized workshops

### PR DESCRIPTION
**Pull request by ChristinaLK**
More information about the types of workshops

I originally proposed this material in the instructor training, but I think it should be here.
I'm open to suggestions, including whether or not it should be on a separate page instead of in the index.

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks for submitting this @ChristinaLK !

I'd like to get @sheraaronhurt to review from the Workshop Admin perspective.

Also we have this line:

>Note that you are free to charge what you choose for a workshop;
this is a perennial topic of discussion among the Carpentries community and there's
a good summary of points here: TBD

Do we have anything to fill the TBD in with yet?

**Comment by ChristinaLK** [comment]
No. In theory I'd like to put something like a blog post together.

**Comment by tracykteal** [comment]
We have a blog post in the works, at the collecting ideas phase.

[Draft workshop fees blog post](https://docs.google.com/document/d/1rrSXSwzzjDY0jiaZuRms6DP1KywYDis_rT5dtcZUOf8/edit)

Mark L, Christina K, Darya V, Rayna H and Chris Prince Udochukwu Njoku have already been contributing.

**Comment by sheraaronhurt** [comment]
@maneesha  I have reviewed and shared some suggestions with the team. They made changes and I am ok with everything.

**Comment by maneesha** [comment]
Is this ready to publish? I still see "TBD" in this PR and the blog post document looks like it's not final yet.  @sheraaronhurt

**Comment by ChristinaLK** [comment]
@maneesha I wrangled together a blog post. once that's posted, I can update this PR. 

Which repo should I submit the blog post to?

**Comment by maneesha** [comment]
I would suggest posting this to the Carpentries blog -- the other blogs are used for information specific to that lesson program.  @serahrono  will review and merge your blog post.  Once that's done we can update and merge this PR.

**Comment by ChristinaLK** [comment]
Blog post is up! I updated the PR. I think we're set?

**Comment by tracykteal** [comment]
Yes! Thanks so much @ChristinaLK and everyone who contributed.

**Comment by sheraaronhurt** [comment]
Awesome post!! I'm certain I will be referencing this post regularly :)

**Comment by serahrono** [comment]
Thank you so much for this contribution @ChristinaLK 🙌

**Pull request merged**
