### PR TITLE
Updated .md file names to reflect changes for instructor development …

### PR DESCRIPTION
**Pull request by kariljordan**
…committee

### CODE REVIEW

**Comment by kariljordan** [comment]
@tobyhodges please review

**Comment by maneesha** [comment]
As with #278 @tobyhodges   please review - if it looks good to you I will merge.

**Comment by maneesha** [comment]
Also pinging @tobyhodges

**Comment by maneesha** [comment]
I was doing some work on a local branch to fix some things here -- I want to look at everything before merging this.

**Comment by maneesha** [comment]
Closing this as this was a bit more complicated than it would seem and  was fixed with a bunch of commits on 2018-11-29

**Pull request closed without merging**
