### PR TITLE
add R inflammation lesson

### PR DESCRIPTION
**Pull request by raynamharris**
Added 3 good starting points and 2 episodes to avoid in the R inflammation lesson.

cc @sstevens2 @karenword

### CODE REVIEW

**Comment by sstevens2** [comment]
I used episode 2 (functions) and it worked well.  I agree with your lessons to avoid and good places to start.  Thanks @raynamharris!

**Comment by raynamharris** [comment]
Excellent! Thanks for the feedback @sstevens2

**Comment by maneesha** [comment]
Would like to see #411 resolved before merging this.

**Comment by raynamharris** [comment]
What remains to have #411 resolved? Approval from the maintainers?

**Pull request merged**
