### PR TITLE
Added subcommittee roles

### PR DESCRIPTION
**Pull request by kariljordan**

### CODE REVIEW

**Comment by maneesha** [comment]
@kariljordan  This document references a bunch of md documents for each role.  Where do all these documents live?

**Comment by ErinBecker** [comment]
@maneesha those are in the mentoring repo and should be moved into the handbook.

**Comment by ErinBecker** [comment]
I recommend we consolidate those roles into a single document.

**Comment by maneesha** [comment]
@kariljordan @ErinBecker   Has this been resolved with all the other changes made to the mentoring section of the handbook?

**Comment by ErinBecker** [comment]
@maneesha - yes, safe to close this one.

**Comment by ErinBecker** [comment]
The mentoring subcommittee roles are now here: https://docs.carpentries.org/topic_folders/mentoring/mentoring-subcommittee-roles.html

The mentoring group roles are here: 
https://docs.carpentries.org/topic_folders/mentoring/mentoring-groups-roles.html

**Pull request closed without merging**
